name: Create Tag and Release

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  set_tag:
    runs-on: ubuntu-latest
    env:
      IS_MERGED: ${{ github.event.pull_request.merged }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if PR is merged
        id: pr_is_merged
        if: ${{github.event.pull_request.merged  == true}}
        # echo "origin_branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
        run: |
          echo "This PR is merged, getting the branch name"
          version=$(echo "${{ github.event.pull_request.head.ref }}" | sed -E 's|.*/([0-9]+\.[0-9]+\.[0-9]+)|\1|' )
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"

      - name: Create Tag
        if: ${{github.event.pull_request.merged  == true}}
        run: |
          echo "Creating tag for version ${{ steps.pr_is_merged.outputs.version }}"
          git tag -a ${{ steps.pr_is_merged.outputs.version }} -m "Release ${{ steps.pr_is_merged.outputs.version }}"
      - name: Push Tag
        run: |
          echo "pushing tag using token $GITHUB_TOKEN"
          git push origin ${{ steps.pr_is_merged.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if PR is not merged
        id: pr_is_not_merged
        if: ${{github.event.pull_request.merged == false}}
        run: echo "This PR is not merged"
