name: Create Tag and Release

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag version
        id: get_tag
        run: echo "tag={$(echo $GITHUB_REF#refs/heads/release/)" >> $GITHUB_OUTPUT
      - name: Print tag version
        run: echo ${{ steps.get_tag.outputs.tag }}
