name: Check branch name to merge main
on:
  pull_request:
    branches:
      - main
jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate branch name is release or hotfix
        id: get_branch_name
        run: |
          echo "Getting the branch name"
          branch_name=${{ github.event.pull_request.head.ref }}
          if ! echo "$branch" | grep -qE '^(release|hotfix)\/[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Branch name is not in the correct format"
            exit 1
          fi
