name: Check branch name to merge develop
on:
  pull_request:
    branches:
      - develop
jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate branch name is feature or bugfix
        id: get_branch_name
        run: |
          echo "Getting the branch name"
          branch_name=$(echo "${{ github.event.pull_request.head.ref }}" | grep -o '^[^/]*' )
          if ! echo "$branch" | grep -qE '^(feature|bugfix)\/[a-z0-9_]+$'; then
            echo "Branch name is not in the correct format"
            exit 1
